apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rolebinding-manager
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create", "get", "list", "watch", "delete"]