apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-service-deployment
  namespace: default
  labels:
    app: banking-service
    env: default
spec:
  selector:
    matchLabels:
      app: banking-service
  template:
    metadata:
      labels:
        app: banking-service
    spec:
      containers:
        - name: banking-service
          image: 147997139534.dkr.ecr.us-east-1.amazonaws.com/cloud/account-service:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: transactionport
          resources:
            limits:
              memory: 512Mi
              cpu: '0.1'
            requests:
              memory: 256Mi
              cpu: '0.05'
          envFrom:
            - secretRef:
                name: banking-service-secret
