apiVersion: v1
kind: Secret
metadata:
  name: banking-service-secret
  namespace: default
type: Opaque
stringData:
  NAME_SERVICE: 'banking-service'
  GRPC_PORT: '50052'
  MONGODB_URI: 'mongodb://localhost:27017/'
  MONGODB_DB_NAME: 'account-service'
  TRANSACTION_SERVICE_HOST: 'transaction-service'
  TRANSACTION_SERVICE_PORT: '50051'
  TRANSACTION_SERVICE_NAME: 'transaction-service'
  TRANSACTION_SERVICE_URI: 'transaction-service:50051'
  TRANSACTION_SERVICE_TIMEOUT: '5s'
  TRANSACTION_SERVICE_RETRIES: '3'
  TRANSACTION_SERVICE_BACKOFF_BASE_DELAY: '1s'
  TRANSACTION_SERVICE_BACKOFF_MAX_DELAY: '10s'
  
