apiVersion: v1
kind: Service
metadata:
  name: banking-service
  labels:
    app: banking-service
spec:
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
      name: grpc-banking
  selector:
    app: banking-service
