# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/account.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/account.proto\x12\x10\x61\x63\x63ount.v1alpha1\"Z\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\x12\x11\n\tcreate_at\x18\x04 \x01(\t\x12\x11\n\tupdate_at\x18\x05 \x01(\t\"1\n!ValidateIfExistAccountNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"4\n\"ValidateIfExistAccountNameResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"5\n\x14\x43reateAccountRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x02\"#\n\x15\x43reateAccountResponse\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x18GetAccountBalanceRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x19GetAccountBalanceResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x02\"2\n\x1cGetTransactionHistoryRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"^\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"T\n\x1dGetTransactionHistoryResponse\x12\x33\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1d.account.v1alpha1.Transaction2\xe7\x03\n\x11\x41\x63\x63ountAPIService\x12\x87\x01\n\x1aValidateIfExistAccountName\x12\x33.account.v1alpha1.ValidateIfExistAccountNameRequest\x1a\x34.account.v1alpha1.ValidateIfExistAccountNameResponse\x12`\n\rCreateAccount\x12&.account.v1alpha1.CreateAccountRequest\x1a\'.account.v1alpha1.CreateAccountResponse\x12l\n\x11GetAccountBalance\x12*.account.v1alpha1.GetAccountBalanceRequest\x1a+.account.v1alpha1.GetAccountBalanceResponse\x12x\n\x15GetTransactionHistory\x12..account.v1alpha1.GetTransactionHistoryRequest\x1a/.account.v1alpha1.GetTransactionHistoryResponseB\x12Z\x10\x61\x63\x63ount/v1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020account/v1alpha1'
  _globals['_ACCOUNT']._serialized_start=41
  _globals['_ACCOUNT']._serialized_end=131
  _globals['_VALIDATEIFEXISTACCOUNTNAMEREQUEST']._serialized_start=133
  _globals['_VALIDATEIFEXISTACCOUNTNAMEREQUEST']._serialized_end=182
  _globals['_VALIDATEIFEXISTACCOUNTNAMERESPONSE']._serialized_start=184
  _globals['_VALIDATEIFEXISTACCOUNTNAMERESPONSE']._serialized_end=236
  _globals['_CREATEACCOUNTREQUEST']._serialized_start=238
  _globals['_CREATEACCOUNTREQUEST']._serialized_end=291
  _globals['_CREATEACCOUNTRESPONSE']._serialized_start=293
  _globals['_CREATEACCOUNTRESPONSE']._serialized_end=328
  _globals['_GETACCOUNTBALANCEREQUEST']._serialized_start=330
  _globals['_GETACCOUNTBALANCEREQUEST']._serialized_end=368
  _globals['_GETACCOUNTBALANCERESPONSE']._serialized_start=370
  _globals['_GETACCOUNTBALANCERESPONSE']._serialized_end=426
  _globals['_GETTRANSACTIONHISTORYREQUEST']._serialized_start=428
  _globals['_GETTRANSACTIONHISTORYREQUEST']._serialized_end=478
  _globals['_TRANSACTION']._serialized_start=480
  _globals['_TRANSACTION']._serialized_end=574
  _globals['_GETTRANSACTIONHISTORYRESPONSE']._serialized_start=576
  _globals['_GETTRANSACTIONHISTORYRESPONSE']._serialized_end=660
  _globals['_ACCOUNTAPISERVICE']._serialized_start=663
  _globals['_ACCOUNTAPISERVICE']._serialized_end=1150
# @@protoc_insertion_point(module_scope)
