# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x10\x61\x63\x63ount.v1alpha1\"Z\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\x12\x11\n\tcreate_at\x18\x04 \x01(\t\x12\x11\n\tupdate_at\x18\x05 \x01(\t\"1\n!ValidateIfExistAccountNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"4\n\"ValidateIfExistAccountNameResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"5\n\x14\x43reateAccountRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x02\"#\n\x15\x43reateAccountResponse\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x18GetAccountBalanceRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x19GetAccountBalanceResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x02\x32\xed\x02\n\x11\x41\x63\x63ountAPIService\x12\x87\x01\n\x1aValidateIfExistAccountName\x12\x33.account.v1alpha1.ValidateIfExistAccountNameRequest\x1a\x34.account.v1alpha1.ValidateIfExistAccountNameResponse\x12`\n\rCreateAccount\x12&.account.v1alpha1.CreateAccountRequest\x1a\'.account.v1alpha1.CreateAccountResponse\x12l\n\x11GetAccountBalance\x12*.account.v1alpha1.GetAccountBalanceRequest\x1a+.account.v1alpha1.GetAccountBalanceResponseB\x12Z\x10\x61\x63\x63ount/v1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020account/v1alpha1'
  _globals['_ACCOUNT']._serialized_start=35
  _globals['_ACCOUNT']._serialized_end=125
  _globals['_VALIDATEIFEXISTACCOUNTNAMEREQUEST']._serialized_start=127
  _globals['_VALIDATEIFEXISTACCOUNTNAMEREQUEST']._serialized_end=176
  _globals['_VALIDATEIFEXISTACCOUNTNAMERESPONSE']._serialized_start=178
  _globals['_VALIDATEIFEXISTACCOUNTNAMERESPONSE']._serialized_end=230
  _globals['_CREATEACCOUNTREQUEST']._serialized_start=232
  _globals['_CREATEACCOUNTREQUEST']._serialized_end=285
  _globals['_CREATEACCOUNTRESPONSE']._serialized_start=287
  _globals['_CREATEACCOUNTRESPONSE']._serialized_end=322
  _globals['_GETACCOUNTBALANCEREQUEST']._serialized_start=324
  _globals['_GETACCOUNTBALANCEREQUEST']._serialized_end=362
  _globals['_GETACCOUNTBALANCERESPONSE']._serialized_start=364
  _globals['_GETACCOUNTBALANCERESPONSE']._serialized_end=420
  _globals['_ACCOUNTAPISERVICE']._serialized_start=423
  _globals['_ACCOUNTAPISERVICE']._serialized_end=788
# @@protoc_insertion_point(module_scope)
