# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import transaction_pb2 as app_dot_proto_dot_transaction__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/proto/transaction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionAPIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferMoney = channel.unary_unary(
                '/transaction.v1alpha1.TransactionAPIService/TransferMoney',
                request_serializer=app_dot_proto_dot_transaction__pb2.TransferMoneyRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_transaction__pb2.TransferMoneyResponse.FromString,
                _registered_method=True)
        self.GetTransactionHistory = channel.unary_unary(
                '/transaction.v1alpha1.TransactionAPIService/GetTransactionHistory',
                request_serializer=app_dot_proto_dot_transaction__pb2.GetTransactionHistoryRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_transaction__pb2.GetTransactionHistoryResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/transaction.v1alpha1.TransactionAPIService/CreateAccount',
                request_serializer=app_dot_proto_dot_transaction__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_transaction__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.ProcessTransaction = channel.unary_unary(
                '/transaction.v1alpha1.TransactionAPIService/ProcessTransaction',
                request_serializer=app_dot_proto_dot_transaction__pb2.TransactionRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_transaction__pb2.TransactionResponse.FromString,
                _registered_method=True)


class TransactionAPIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransferMoney(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionAPIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferMoney': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferMoney,
                    request_deserializer=app_dot_proto_dot_transaction__pb2.TransferMoneyRequest.FromString,
                    response_serializer=app_dot_proto_dot_transaction__pb2.TransferMoneyResponse.SerializeToString,
            ),
            'GetTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionHistory,
                    request_deserializer=app_dot_proto_dot_transaction__pb2.GetTransactionHistoryRequest.FromString,
                    response_serializer=app_dot_proto_dot_transaction__pb2.GetTransactionHistoryResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=app_dot_proto_dot_transaction__pb2.CreateAccountRequest.FromString,
                    response_serializer=app_dot_proto_dot_transaction__pb2.CreateAccountResponse.SerializeToString,
            ),
            'ProcessTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTransaction,
                    request_deserializer=app_dot_proto_dot_transaction__pb2.TransactionRequest.FromString,
                    response_serializer=app_dot_proto_dot_transaction__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction.v1alpha1.TransactionAPIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transaction.v1alpha1.TransactionAPIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionAPIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransferMoney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.v1alpha1.TransactionAPIService/TransferMoney',
            app_dot_proto_dot_transaction__pb2.TransferMoneyRequest.SerializeToString,
            app_dot_proto_dot_transaction__pb2.TransferMoneyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.v1alpha1.TransactionAPIService/GetTransactionHistory',
            app_dot_proto_dot_transaction__pb2.GetTransactionHistoryRequest.SerializeToString,
            app_dot_proto_dot_transaction__pb2.GetTransactionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.v1alpha1.TransactionAPIService/CreateAccount',
            app_dot_proto_dot_transaction__pb2.CreateAccountRequest.SerializeToString,
            app_dot_proto_dot_transaction__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.v1alpha1.TransactionAPIService/ProcessTransaction',
            app_dot_proto_dot_transaction__pb2.TransactionRequest.SerializeToString,
            app_dot_proto_dot_transaction__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
