# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import account_pb2 as account__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in account_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountAPIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateIfExistAccountName = channel.unary_unary(
                '/account.v1alpha1.AccountAPIService/ValidateIfExistAccountName',
                request_serializer=account__pb2.ValidateIfExistAccountNameRequest.SerializeToString,
                response_deserializer=account__pb2.ValidateIfExistAccountNameResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/account.v1alpha1.AccountAPIService/CreateAccount',
                request_serializer=account__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=account__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.GetAccountBalance = channel.unary_unary(
                '/account.v1alpha1.AccountAPIService/GetAccountBalance',
                request_serializer=account__pb2.GetAccountBalanceRequest.SerializeToString,
                response_deserializer=account__pb2.GetAccountBalanceResponse.FromString,
                _registered_method=True)


class AccountAPIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateIfExistAccountName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountAPIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateIfExistAccountName': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateIfExistAccountName,
                    request_deserializer=account__pb2.ValidateIfExistAccountNameRequest.FromString,
                    response_serializer=account__pb2.ValidateIfExistAccountNameResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=account__pb2.CreateAccountRequest.FromString,
                    response_serializer=account__pb2.CreateAccountResponse.SerializeToString,
            ),
            'GetAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalance,
                    request_deserializer=account__pb2.GetAccountBalanceRequest.FromString,
                    response_serializer=account__pb2.GetAccountBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'account.v1alpha1.AccountAPIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('account.v1alpha1.AccountAPIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountAPIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateIfExistAccountName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.v1alpha1.AccountAPIService/ValidateIfExistAccountName',
            account__pb2.ValidateIfExistAccountNameRequest.SerializeToString,
            account__pb2.ValidateIfExistAccountNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.v1alpha1.AccountAPIService/CreateAccount',
            account__pb2.CreateAccountRequest.SerializeToString,
            account__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.v1alpha1.AccountAPIService/GetAccountBalance',
            account__pb2.GetAccountBalanceRequest.SerializeToString,
            account__pb2.GetAccountBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
