apiVersion: v1
kind: Secret
metadata:
  name: transaction-service-secret
  namespace: develop
type: Opaque
stringData:
  NAME_SERVICE: 'transaction-service'
  GRPC_PORT: '0.0.0.0:50051'
  MONGODB_URI: 'mongodb://localhost:27017/'
  MONGODB_DB_NAME: 'transaction-service'
  ACCOUNT_SERVICE_HOST: 'banking-service'
  ACCOUNT_SERVICE_PORT: '50051'
  ACCOUNT_SERVICE_NAME: 'banking-service'
  ACCOUNT_SERVICE_URI: 'banking-service:50051'
  ACCOUNT_SERVICE_TIMEOUT: '5s'
  ACCOUNT_SERVICE_RETRIES: '3'
